# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
  - openjdk11

script:
  - ./gradlew clean build

# Отправлять уведомление на почту gh0st84@mail.ru
notifications:
  email:
    recipients:
      - gh0st84@mail.ru
    on_success: never # default: change
    on_failure: always # default: always